id: P007002
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5033
  title: དཔལ་གསང་བའི་སྙིང་པོ་དེ་ཁོ་ན་ཉིད་ངེས་པའི་རྒྱུད་ཀྱི་འགྲེལ་པ་གསང་བདག་དགོངས་རྒྱན།
  author: ''
  volumes:
    5248ac8d6abc4c63b6885ba10bade026:
      image_group_id: I3CN5035
      title: ''
      volume_number: 1
      total_pages: 400
ebook_metadata:
  title: དཔལ་གསང་བའི་སྙིང་པོ་དེ་ཁོ་ན་ཉིད་ངེས་པའི་རྒྱུད་ཀྱི་འགྲེལ་པ་གསང་བདག་དགོངས་རྒྱན།
  author: ''
  sku: P007002
  cover: cover.jpg
  layers:
  - pagination
