id: I487D142F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T14:35:54+00:00'
last_modified: '2022-06-08T10:59:43.579945+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5033
  title: དཔལ་གསང་བའི་སྙིང་པོ་དེ་ཁོ་ན་ཉིད་ངེས་པའི་རྒྱུད་ཀྱི་འགྲེལ་པ་གསང་བདག་དགོངས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B8C9:
      image_group_id: I3CN5035
      title: Volume 1 of dpal gsang ba'i snying po de kho na nyid nges pa'i rgyud
        kyi 'grel pa gsang bdag dgongs rgyan/
      total_pages: 400
      order: 1
      base_file: B8C9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
