id: I487D142F
legacy_id: P007002
ocr_import_info:
  bdrc_scan_id: W3CN5033
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T14:33:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:55:11.320415+00:00'
last_modified: 2022-08-27 19:55:34.076630
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5033
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5033
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་གསང་བའི་སྙིང་པོ་དེ་ཁོ་ན་ཉིད་ངེས་པའི་རྒྱུད་ཀྱི་འགྲེལ་པ་གསང་བདག་དགོངས་རྒྱན།
  author: ཨོ་རྒྱན་ཆོས་ཀྱི་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9684857547991724
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN5035:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5035
      total_pages: 400
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5035.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9684857547991724
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
